@file:Suppress("PropertyName", "SpellCheckingInspection")

/*
* This file was generated by the Gradle 'init' task.
*
* The settings file is used to specify which projects to include in your build.
* For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
* This project uses @Incubating APIs which are subject to change.
*/

pluginManagement {
        repositories {
                mavenLocal()
                mavenCentral()
                gradlePluginPortal()
                maven("https://repo.polyfrost.org/releases") {
                        name = "PolyFrost Repo"
                }
        }
        plugins {
                id("org.polyfrost.multi-version.root") version "0.6.7"
        }
}

plugins {
        // Apply the foojay-resolver plugin to allow automatic download of JDKs
        id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

val mod_name: String by settings
rootProject.name = mod_name

val version_kotlin: String by settings
val version_shadow: String by settings
val version_idea_ext: String by settings

val libz by dependencyResolutionManagement.versionCatalogs.registering {
        version("kotlin", version_kotlin)
        version("shadow", version_shadow)
        version("idea-ext", version_idea_ext)
        
        plugin("idea-ext", "org.jetbrains.gradle.plugin.idea-ext").versionRef("idea-ext")
        plugin("shadow", "com.github.johnrengelman.shadow").versionRef("shadow")
}

arrayOf(
        "1.8.9-forge"
).forEach {
        include(":$it")
        project(":$it").apply {
                projectDir = file("versions/$it")
                buildFileName = "../../build-mod.gradle.kts"
        }
}